version: "3.9"
   
services: 
    redismaster:
        image: 'bitnami/redis'
        restart: always
        sysctls:
            net.core.somaxconn: 65365
        environment:
            - REDIS_REPLICATION_MODE=master
            - REDIS_PASSWORD=123

    redisslave:
        image: 'bitnami/redis'
        restart: always
        sysctls:
            net.core.somaxconn: 65365
        depends_on:
            - redismaster
        environment:
            - REDIS_REPLICATION_MODE=slave
            - REDIS_MASTER_HOST=tasks.redismaster
            - REDIS_MASTER_PASSWORD=123
            - REDIS_PASSWORD=123
        deploy:
            replicas: 2
            placement:
               max_replicas_per_node: 1

    redissentinel:
        image: 'bitnami/redis-sentinel'
        restart: always
        sysctls:
            net.core.somaxconn: 65365
        depends_on:
            - redismaster
            - redisslave
        environment:
            - REDIS_MASTER_HOST=tasks.redismaster
            - REDIS_MASTER_PASSWORD=123
            - REDIS_PASSWORD=123
        deploy:
            replicas: 3
            placement:
               max_replicas_per_node: 1
    
    centrifugo:
        image: centrifugo/centrifugo:v3.2
        environment:
            - CENTRIFUGO_ENGINE=redis
            - CENTRIFUGO_REDIS_SENTINEL_ADDRESS=tasks.redissentinel:26379
            - CENTRIFUGO_REDIS_SENTINEL_MASTER_NAME=mymaster
            - CENTRIFUGO_REDIS_PASSWORD=123
            - CENTRIFUGO_ADMIN_PASSWORD=321
            - CENTRIFUGO_ADMIN_SECRET=11
            - CENTRIFUGO_API_KEY=33
            - CENTRIFUGO_TOKEN_HMAC_SECRET_KEY=222
            - CENTRIFUGO_PROMETHEUS=true
            - CENTRIFUGO_ALLOWED_ORIGINS=*
        command: centrifugo --admin
        ports:
            - 8000:8000
        ulimits:
            nofile:
                soft: 65535
                hard: 65535
        depends_on:
            - redismaster
            - redisslave
            - redissentinel
        deploy:
            replicas: 6
            placement:
               max_replicas_per_node: 2
            
    prometheus:
        image: ismkdc/centrifugo-prometheus
        depends_on:
            - centrifugo
    
    grafana:
        image: grafana/grafana
        environment:
            - GF_SECURITY_ADMIN_USER=gfadmin
            - GF_SECURITY_ADMIN_PASSWORD=gfpass
        ports:
            - 3000:3000
